import Foundation

public typealias MaterialLibraryService = GeneralDraftLibraryService
public typealias MaterialLibraryReport = GeneralDraftLibraryReport
public typealias MaterialLibraryItem = GeneralDraftLibraryItem
public typealias MaterialLibraryPackageEntry = GeneralDraftLibraryPackageEntry
public typealias MaterialLibraryPackagePlan = GeneralDraftLibraryPackagePlan
public typealias MaterialLibraryBackupFile = GeneralDraftBackupFile
public typealias MaterialLibraryBackupPlan = GeneralDraftBackupPlan
public typealias MaterialLibraryBackupWriteResult = GeneralDraftBackupWriteResult
public typealias MaterialLibraryReusePlan = GeneralDraftReusePlan
public typealias MaterialLibraryReuseStatus = GeneralDraftReuseStatus
public typealias MaterialLibraryReuseRiskLevel = GeneralDraftReuseRiskLevel
public typealias MaterialLibrarySourceSnapshot = GeneralDraftReuseSourceSnapshot
