// Generated by script/generate_browser_extension_protocol.py. Do not edit.

extension BrowserExtensionProtocol {
  public static let activeBrowserExtensions = [
    "safari",
    "chrome",
  ]
  public static let safariWebExtensionBundleID =
    "com.jinfang.PersonalSitePublisherMac.SafariExtension"
  public static let chromiumDevelopmentExtensionID =
    "lnibkmfhfikfbkeehcjbiaalhkiankam"
  public static let chromeProductionExtensionID: String? =
    "ginjcibepmeobaaadmfiagigcpcebmcc"
  public static let loopbackHost = "127.0.0.1"
  public static let loopbackPort: UInt16 = 17843
  public static let loopbackBaseURL =
    "http://\(loopbackHost):\(loopbackPort)"
  public static let loopbackProtocolHeaderName =
    "X-RepoPress-Protocol"
  public static let loopbackProtocolHeaderValue =
    "1"
  public static let maximumInputBytes = 50_331_648
  public static let statusPayloadVersion = 6
  public static let accessControlAllowHeaders =
    "Authorization, Content-Type, \(loopbackProtocolHeaderName)"

  public static let allowedRoutes: [String: Set<String>] = [
    "/v1/folders": ["GET"],
    "/v1/import": ["POST"],
    "/v1/open": ["POST"],
    "/v1/status": ["GET"],
    "/v1/suggestions": ["POST"],
  ]
}
