// Generated by script/generate_browser_extension_protocol.py. Do not edit.

extension KnowledgeNativeMessagingProtocol {
  public static let schemaVersion = 1
  public static let hostName = "com.jinfang.personal_site_publisher.knowledge"
  public static let firefoxExtensionID = "knowledge-capture@jinfang.local"
  public static let activeBrowserExtensions = [
    "safari",
    "chrome",
  ]
  public static let safariWebExtensionBundleID =
    "com.jinfang.PersonalSitePublisherMac.SafariExtension"
  public static let chromiumDevelopmentExtensionID =
    "lnibkmfhfikfbkeehcjbiaalhkiankam"
  public static let chromiumDevelopmentOrigin =
    "chrome-extension://\(chromiumDevelopmentExtensionID)/"
  public static let chromeProductionExtensionID: String? =
    "ginjcibepmeobaaadmfiagigcpcebmcc"
  public static let edgeProductionExtensionID: String? =
    nil
  public static let loopbackHost = "127.0.0.1"
  public static let loopbackPort: UInt16 = 17843
  public static let loopbackBaseURL =
    "http://\(loopbackHost):\(loopbackPort)"
  public static let loopbackProtocolHeaderName =
    "X-RepoPress-Protocol"
  public static let loopbackProtocolHeaderValue =
    "1"
  public static let chromeAllowedOrigins = [
    "chrome-extension://lnibkmfhfikfbkeehcjbiaalhkiankam/",
    "chrome-extension://ginjcibepmeobaaadmfiagigcpcebmcc/",
  ]
  public static let edgeAllowedOrigins = [
    "chrome-extension://lnibkmfhfikfbkeehcjbiaalhkiankam/",
  ]
  public static let maximumInputBytes = 52_428_800
  public static let maximumOutputBytes = 1_048_576

  static let allowedRoutes: [String: Set<String>] = [
    "/v1/folders": ["GET"],
    "/v1/import": ["POST"],
    "/v1/open": ["POST"],
    "/v1/suggestions": ["POST"],
  ]
}
